
FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache git
COPY package.json .npmrc .nvmrc tsconfig.base.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/
COPY packages/db/package.json ./packages/db/
RUN npm install
COPY . .
RUN npm run db:generate && npm run build
EXPOSE 3000
CMD ["npm", "run", "start", "-w", "apps/web"]
