
import { MockGitHubService } from "@tern/github";
const svc = new MockGitHubService();
const pr = await svc.createPullRequest({
  installationId: 123456,
  owner: "tern-demo",
  repo: "acmepay-demo",
  title: "fix: migrate for AcmePay v2",
  body: "Migration generated by Tern demo.",
  head: `tern/api-migration-${Date.now()}`,
  base: "main"
});
console.log(`PR created: ${pr.url}`);
