
import { DefaultSpecLoader, DefaultDiffEngine } from "@tern/openapi";
import { TreeSitterScanner } from "@tern/scanner";
import { DefaultMigrationEngine } from "@tern/migration-engine";
import { DefaultSandboxRunner } from "@tern/sandbox";
import { MockGitHubService } from "@tern/github";
import path from "path";
const repoPath = path.join(process.cwd(), "demo", "broken-app");
const loader = new DefaultSpecLoader();
const oldSpec = await loader.load("demo/acmepay-openapi-v1.yaml");
const newSpec = await loader.load("demo/acmepay-openapi-v2.yaml");
const changes = await new DefaultDiffEngine().diff(oldSpec, newSpec);
console.log(`Breaking changes: ${changes.length}`);
changes.forEach(c => console.log(`  - ${c.type}: ${c.description}`));
const usages = await new TreeSitterScanner().scan(repoPath, changes);
console.log(`Affected usages: ${usages.length}`);
const patches = await new DefaultMigrationEngine().generatePatches(repoPath, changes, usages);
const valid = patches.filter(p => p.validationStatus === "valid");
console.log(`Valid patches: ${valid.length}/${patches.length}`);
const result = await new DefaultSandboxRunner().run(repoPath, "npm test", { timeoutMs: 120000 });
console.log(`Sandbox: ${result.status}`);
const svc = new MockGitHubService();
const pr = await svc.createPullRequest({
  installationId: 123456,
  owner: "tern-demo",
  repo: "acmepay-demo",
  title: "fix: migrate for AcmePay v2",
  body: "Migration generated by Tern demo.",
  head: `tern/api-migration-${Date.now()}`,
  base: "main"
});
console.log(`PR: ${pr.url}`);
