
import { BreakingChange, AffectedUsage, MigrationPatch, SandboxResult } from "@tern/shared";
import { PullRequestReport } from "./interfaces";

export function buildPullRequestReport(
  changes: BreakingChange[],
  usages: AffectedUsage[],
  patches: MigrationPatch[],
  sandbox: SandboxResult
): PullRequestReport {
  const breakingCount = changes.filter(c => c.severity === "breaking").length;
  const riskyCount = changes.filter(c => c.severity === "risky").length;
  const affectedFiles = [...new Set(usages.map(u => u.file))].sort();
  const validPatches = patches.filter(p => p.validationStatus === "valid");
  const avgConfidence = validPatches.length ? validPatches.reduce((acc, p) => acc + (p.confidence || 0), 0) / validPatches.length : 0;
  const warnings: string[] = [];
  if (sandbox.status !== "passed") warnings.push(`Sandbox tests did not pass (${sandbox.status}). Review before merging.`);
  if (usages.some(u => u.confidence === "low")) warnings.push("Some affected usages were detected with low confidence. Manual verification recommended.");
  if (validPatches.length === 0) warnings.push("No valid patches were generated. This migration may require manual intervention.");

  const apiDiffSummary = [
    `| Severity | Type | Description |`,
    `|---|---|---|`,
    ...changes.map(c => `| ${c.severity} | ${c.type} | ${c.description} |`)
  ].join("\n");

  const checklist = [
    "[ ] Review each changed file for semantic correctness.",
    "[ ] Verify that API responses are handled correctly.",
    "[ ] Run the full test suite locally.",
    "[ ] Check that no secrets or credentials were added.",
    "[ ] Confirm no unrelated files were modified.",
    "[ ] Validate the migration against your own API documentation.",
    "[ ] Approve and merge once satisfied."
  ];

  return {
    executiveSummary: `This PR automatically migrates the repository to be compatible with a new API specification. **${breakingCount}** breaking and **${riskyCount}** risky changes were detected. **${validPatches.length}** patches passed validation.`,
    apiDiffSummary,
    affectedFiles,
    migrationReasoning: validPatches.map(p => `- **${p.filePath}**: ${p.description}\n  - Confidence: ${((p.confidence || 0) * 100).toFixed(0)}%\n  - Rules: ${(p.appliedRules || []).join(", ") || "LLM fallback"}`).join("\n\n"),
    confidenceScore: avgConfidence,
    testsExecuted: `Sandbox result: **${sandbox.status}** (${sandbox.durationMs}ms).\n\n${sandbox.testSummary || "No test summary available"}`,
    warnings,
    manualReviewChecklist: checklist
  };
}

export function renderPullRequestBody(report: PullRequestReport): string {
  return [
    "## Executive Summary",
    report.executiveSummary,
    "",
    "## API Diff Summary",
    report.apiDiffSummary,
    "",
    "## Affected Files",
    report.affectedFiles.length ? report.affectedFiles.map(f => `- ${f}`).join("\n") : "_No affected files detected._",
    "",
    "## Migration Reasoning",
    report.migrationReasoning || "_No migration patches were generated._",
    "",
    "## Test Results",
    report.testsExecuted,
    "",
    "## Warnings",
    report.warnings.length ? report.warnings.map(w => `⚠️ ${w}`).join("\n") : "_No warnings._",
    "",
    "## Manual Review Checklist",
    report.manualReviewChecklist.join("\n"),
    "",
    "---",
    "_Generated by [Tern](https://github.com/akkki8844/tern). Human review required._"
  ].join("\n");
}
