
import { BreakingChange, AffectedUsage, MigrationPatch, SandboxResult } from "@tern/shared";
import { PullRequestReport } from "./interfaces";

export function buildPullRequestReport(
  changes: BreakingChange[],
  usages: AffectedUsage[],
  patches: MigrationPatch[],
  sandbox: SandboxResult
): PullRequestReport {
  const breakingCount = changes.filter(c => c.severity === "breaking").length;
  const riskyCount = changes.filter(c => c.severity === "risky").length;
  const affectedFiles = [...new Set(usages.map(u => u.file))].sort();
  const validPatches = patches.filter(p => p.validationStatus === "valid");
  const avgConfidence = validPatches.length ? validPatches.reduce((acc, p) => acc + (p.confidence || 0), 0) / validPatches.length : 0;
  const warnings: string[] = [];
  if (sandbox.status !== "passed") warnings.push(`Sandbox tests did not pass (${sandbox.status}). Review before merging.`);
  if (usages.some(u => u.confidence === "low")) warnings.push("Some affected usages were detected with low confidence. Manual verification recommended.");
  if (validPatches.length === 0) warnings.push("No valid patches were generated. This migration may require manual intervention.");
  const rejectedPatches = patches.filter(p => p.validationStatus !== "valid");
  if (rejectedPatches.length) warnings.push(`${rejectedPatches.length} patch(es) were rejected by the validator. Review the migration report for details.`);

  const changeRows = changes.map(c => `| ${c.severity} | ${c.type} | ${escapeMd(c.description)} | ${c.method || ""} | ${c.path} |`);

  const callSiteRows = usages.map(u => `| ${u.file}:${u.line} | ${escapeMd(u.functionName)} | ${u.httpMethod || ""} | ${u.confidence} | ${escapeMd(u.snippet.slice(0, 60))} |`);

  const patchSummary = validPatches.map(p => {
    const confidence = ((p.confidence || 0) * 100).toFixed(0);
    const rules = (p.appliedRules || []).join(", ") || "LLM fallback";
    return `| ${p.filePath} | ${confidence}% | ${rules} | ${p.lineCountChanged} |`;
  });

  return {
    executiveSummary: `This PR automatically migrates the repository to be compatible with a new API specification. **${breakingCount}** breaking and **${riskyCount}** risky changes were detected across **${affectedFiles.length}** file(s). **${validPatches.length}** patches passed validation.`,
    apiDiffSummary: ["| Severity | Type | Description | Method | Path |", "|---|---|---|---|---|", ...changeRows].join("\n"),
    affectedFiles,
    affectedCallSites: ["| File | Function | Method | Confidence | Snippet |", "|---|---|---|---|---|", ...callSiteRows].join("\n"),
    migrationReasoning: validPatches.map(p => `- **${p.filePath}**: ${p.description}\n  - Confidence: ${((p.confidence || 0) * 100).toFixed(0)}%\n  - Rules: ${(p.appliedRules || []).join(", ") || "LLM fallback"}\n  - Lines changed: ${p.lineCountChanged}`).join("\n\n") || "_No migration patches were generated._",
    confidenceScore: avgConfidence,
    testsExecuted: `Sandbox result: **${sandbox.status}** (${sandbox.durationMs}ms).\n\n${sandbox.testSummary || "No test summary available"}`,
    warnings,
    manualReviewChecklist: [
      "[ ] Review each changed file for semantic correctness.",
      "[ ] Verify that API responses are handled correctly.",
      "[ ] Run the full test suite locally.",
      "[ ] Check that no secrets or credentials were added.",
      "[ ] Confirm no unrelated files were modified.",
      "[ ] Validate the migration against your own API documentation.",
      "[ ] Approve and merge once satisfied."
    ]
  };
}

export function renderPullRequestBody(report: PullRequestReport): string {
  return [
    "## Executive Summary",
    report.executiveSummary,
    "",
    "## API Diff Summary",
    report.apiDiffSummary,
    "",
    "## Affected Files",
    report.affectedFiles.length ? report.affectedFiles.map(f => `- ${f}`).join("\n") : "_No affected files detected._",
    "",
    "## Affected Call Sites",
    report.affectedCallSites,
    "",
    "## Migration Reasoning",
    report.migrationReasoning,
    "",
    "## Test Results",
    report.testsExecuted,
    "",
    "## Warnings",
    report.warnings.length ? report.warnings.map(w => `⚠️ ${w}`).join("\n") : "_No warnings._",
    "",
    "## Manual Review Checklist",
    report.manualReviewChecklist.join("\n"),
    "",
    "---",
    "_Generated by [Tern](https://github.com/akkki8844/tern). Human review required._"
  ].join("\n");
}

function escapeMd(text: string): string {
  return text.replace(/\|/g, "\|").replace(/\n/g, " ");
}
